### PR TITLE
fix: if response does not contain valid JSON throw error #409

### LINKED ISSUE #409: If response is not valid json, but the log or text from SAS, it should throw error
Currently `then()` is being called.

### PR DESCRIPTION
**Pull request by sabhas**
## Issue

Closes #409 

## Intent

If valid JSON cannot be extracted from the response, we should throw an error

## Implementation

parsing the response as JSON.parse(response); if there is any  problem in parsing it would throw error.

## Checks

- [x] Code is formatted correctly (`npm run lint:fix`).
image
- [x] All unit tests are passing (`npm test`).
adapter-unit-tests
- [x] All `sasjs-cli` unit tests are passing (`npm test`).
Mocked:
image
Server:
image
- [x] All `sasjs-tests` are passing (instructions available [here](https://github.com/sasjs/adapter/blob/master/sasjs-tests/README.md)).
screencapture-sas-analytium-co-uk-sabhas-sasjs-test-2021-06-20-23_54_37

### CODE REVIEW

File: src/request/RequestClient.ts [hunk 1]
```diff
@@ -419,7 +420,13 @@ export class RequestClient implements HttpClient {
       }
     } catch {
       try {
-        parsedResponse = JSON.parse(parseWeboutResponse(response.data))
+        const weboutResponse = parseWeboutResponse(response.data)
+        if (weboutResponse === '') {
+          throw new Error('Valid JSON could not be extracted from response.')
+        }
+        console.log('RequestClient')
```
Comment (krishna-acondy) [inline src/request/RequestClient.ts:427]: I think we can remove this (and other) console.log statements that might be left over.

**Review by VladislavParhomchik — DISMISSED** [review]

File: src/request/RequestClient.ts (hunk 1 above)
Comment (sabhas) [reply src/request/RequestClient.ts]: removed

**Review by YuryShkoda — APPROVED** [review]
