### PR TITLE
fix: return requestPromise from sas9JobExecutor

### LINKED ISSUE #677: return requestPromise from sas9JobExecutor as we are returning from other executors

### PR DESCRIPTION
**Pull request by sabhas**
## Issue

closes #677

## Intent

* returns a promise from execute method of SAS9JobExecutor.

## Implementation

What code changes have been made to achieve the intent.

## Checks

No PR (that involves a non-trivial code change) should be merged, unless all items below are confirmed!  If an urgent fix is needed - use a tar file.

- [ ] All `sasjs-cli` unit tests are passing (`npm test`).
- [ ] All `sasjs-tests` are passing (instructions available [here](https://github.com/sasjs/adapter/blob/master/sasjs-tests/README.md)).
- [ ] [Data Controller](https://datacontroller.io) builds and is functional on both SAS 9 and Viya

### CODE REVIEW

File: src/job-execution/Sas9JobExecutor.ts [hunk 1]
```diff
@@ -74,26 +74,32 @@ export class Sas9JobExecutor extends BaseJobExecutor {
...
+          resolve(res)
+        })
+        .catch((err: any) => {
+          // by default error string is equal to actual error object
+          let errString = err
+
+          // if error object contains non empty result attribute, set result to errString
+          if (err.result && err.result !== '') errString = err.result
+          // if there's no result but error message, set error message to errString
+          else if (err.message) errString = err.message
```
Comment (allanbowe) [inline src/job-execution/Sas9JobExecutor.ts:94]: The comments here don't really add anything beyond what the code is doing.  Might be interesting to say why we would get an error message but no result.

Comment (sabhas) [reply src/job-execution/Sas9JobExecutor.ts:94]: I'm not sure about the scenarios when this would happen. Do you have any idea?

Comment (allanbowe) [reply src/job-execution/Sas9JobExecutor.ts:94]: No, not a clue, but presumably the logic is here for a reason?  And it's these reasons that need to be ideally captured in the comments..

**Review by medjedovicm — APPROVED** [review]
