### PR TITLE
fix: file upload with debug enabled

### LINKED ISSUE #170: enable `_debug` and '_contextname' for file upload
FileUploader [issue](https://github.com/sasjs/fileuploader/issues/2) is waiting for adapter to enable debug in request.

### PR DESCRIPTION
**Pull request by sabhas**
## Issue

closes #170 

## Intent

When querying a Viya job using the Web approach (as opposed to using the APIs) with _DEBUG enabled, the first response contains the log with the content in an iframe.

## Implementation

when debug is enabled, and the serverType is VIYA, and useComputeApi is null (WEB), we call parseSasViyaDebugResponse to extract the (_webout) content from the iframe.

## Checks

No PR (that involves a non-trivial code change) should be merged, unless all four of the items below are confirmed!  If an urgent fix is needed - use a tar file.

- [x] Code is formatted correctly (`npm run lint:fix`).
image
- [x] All unit tests are passing (`npm test`).
image
- [x] All `sasjs-cli` unit tests are passing (`npm test`).
Mocked:
image
Server:
image
- [x] All `sasjs-tests` are passing (instructions available [here](https://github.com/sasjs/adapter/blob/master/sasjs-tests/README.md)).
image

### CODE REVIEW

File: src/FileUploader.ts [hunk 1]
```diff
@@ -63,13 +63,28 @@ export class FileUploader {
...
+          )
+          return typeof jsonResponse === 'string'
+            ? isValidJson(jsonResponse)
+            : jsonResponse
+        }
 
-        result =
-          typeof res.result === 'string' ? JSON.parse(res.result) : res.result
+        return typeof res.result === 'string'
+          ? isValidJson(res.result)
```
Comment (allanbowe) [inline src/FileUploader.ts:85]: I wonder if this function should actually be renamed, now that it actually returns JSON as opposed to a boolean?

File: src/FileUploader.ts [hunk 2]
```diff
@@ -63,13 +63,28 @@ export class FileUploader {
 
     return this.requestClient
       .post(uploadUrl, formData, undefined, 'application/json', headers)
-      .then((res) => {
-        let result
+      .then(async (res) => {
+        // for web approach on Viya
+        if (
+          this.sasjsConfig.debug &&
+          (this.sasjsConfig.useComputeApi === null ||
```
Comment (YuryShkoda) [inline src/FileUploader.ts:70]: this condition can never be `true`

File: src/SASjs.ts [hunk 3]
```diff
@@ -540,11 +540,22 @@ export default class SASjs {
...
    */
-  public uploadFile(sasJob: string, files: UploadFile[], params: any) {
-    const fileUploader =
-      this.fileUploader ||
-      new FileUploader(this.sasjsConfig, this.jobsPath, this.requestClient!)
+  public uploadFile(
+    sasJob: string,
+    files: UploadFile[],
+    params: any,
+    config?: any
```
Comment (YuryShkoda) [inline src/SASjs.ts:549]: Please be more specific on type declaration, `config` is at least an object.

File: src/utils/getValidJson.ts [hunk 4]
```diff
@@ -2,7 +2,7 @@
  * Checks if string is in valid JSON format else throw error.
  * @param str - string to check.
  */
-export const isValidJson = (str: string | object) => {
+export const getValidJson = (str: string | object) => {
```
Comment (YuryShkoda) [inline src/utils/getValidJson.ts:5]: I would prefer to have two separate utils.

**Comment by allanbowe** [comment]
We don’t need isValid - just noticed the description needs updating too

**Comment by krishna-acondy** [comment]
Do we know if the CLI tests and sasjs-tests have been run against this PR? It'd be good to tick those boxes in the PR description if they have passed.

**Review by VladislavParhomchik — APPROVED** [review]

File: src/utils/getValidJson.ts (hunk 4 above)
Comment (medjedovicm) [reply src/utils/getValidJson.ts:5]: We are parsing JSON to check if it's valid so since we don't want to parse again and again we decided to return it after checking to optimize the process.

**Review by allanbowe — APPROVED** [review]
