### PR TITLE
When expires csrf token, re-fetch and empty webout fix

### LINKED ISSUE #711: sasjs-server: when XSRF_TOKEN expires, following requests doesn't trigger login callback
When CSRF and connect.sid are present and XSRF token is expired - and you send a request, sasjs server will return `Invalid CSRF token!` in such case adapter should show login modal and after login, resend waiting requests. As usual.

### PR DESCRIPTION
**Pull request by medjedovicm**
## Issue

Fixes #711 

## Intent

- Fix: infinite Promise waiting when webout empty
- Fix: when csrf token expired or not present, re-fetch it automatically.

## Implementation

- Created new error type `InvalidCsrfToken`
- Throwing error when matched
- Re-fetching token and resending request 

## Checks

No PR (that involves a non-trivial code change) should be merged, unless all items below are confirmed!  If an urgent fix is needed - use a tar file.

- [ ] All `sasjs-cli` unit tests are passing (`npm test`).
- (CI Runs this) All `sasjs-tests` are passing. If you want to run it manually (instructions available [here](https://github.com/sasjs/adapter/blob/master/sasjs-tests/README.md)).
- [ ] [Data Controller](https://datacontroller.io) builds and is functional on both SAS 9 and Viya

### CODE REVIEW

File: src/request/RequestClient.ts [hunk 1]
```diff
@@ -584,9 +603,17 @@ export class RequestClient implements HttpClient {
 export const throwIfError = (response: AxiosResponse) => {
   switch (response.status) {
     case 400:
-      if (typeof response.data === 'object') {
+      if (
+        typeof response.data === 'object' &&
+        response.data.error === 'invalid_grant'
+      ) {
+        // In SASVIYA when trying to get access token, if auth code is wrong status code will be 400 so in such case we return login required error.
```
Comment (allanbowe) [inline src/request/RequestClient.ts:610]: 👍

**Review by sabhas — APPROVED** [review]

**Review by saadjutt01 — APPROVED** [review]
