### PR TITLE
fix: Issue 276

### LINKED ISSUE #276: sasjs request should perform validations on the input data object
For example:

```
"indata": [
  [{"data": "value"}]
]
```

### PR DESCRIPTION
**Pull request by sabhas**
## Issue

fixes #276 
## Intent

Validate table structure and table name.

## Implementation

Added a new method validateInput to verify provided input data is  in correct form and table names follows the rules.

## Checks

- [x] Code is formatted correctly (`npm run lint:fix`).
- [x] All unit tests are passing (`npm test`).
adapter-unit-tests
- [ ] All `sasjs-cli` unit tests are passing (`npm test`).
- [x] All `sasjs-tests` are passing (instructions available [here](https://github.com/sasjs/adapter/blob/master/sasjs-tests/README.md)).
screencapture-sas-analytium-co-uk-sabhas-sasjs-test-2021-06-11-17_45_35

### CODE REVIEW

File: src/SASjs.ts [hunk 1]
```diff
@@ -577,19 +595,71 @@ export default class SASjs {
...
+  private validateInput(data: { [key: string]: any }): {
+    status: boolean
+    msg: string
+  } {
+    if (data === null) return { status: true, msg: '' }
+    for (const key in data) {
+      if (key.match(/^[a-zA-Z_]/)) {
+        if (key.match(/^[a-zA-Z_][a-zA-Z0-9_]*$/)) {
+          if (key.length <= 32) {
+            if (this.getType(data[key]) === 'Array') {
```
Comment (medjedovicm) [inline src/SASjs.ts:618]: My personal preference would be to escape the nesting for the sake of better readability.
My suggestion is to do something like this:

```
// On every false condition you return with an error

if (!key.match(/^[a-zA-Z_]/)) {
  return {
    status: false,
    msg: 'First letter of table should be alphabet or underscore.'
  }
}

if (!key.match(/^[a-zA-Z_][a-zA-Z0-9_]*$/)) {
  return { status: false, msg: 'Table name should be alphanumeric.' }
}

// Finally if all are true, none of them were called, so you are left with returning the results.

return { status: true, msg: '' }
```

**Review by medjedovicm — CHANGES_REQUESTED** [review]

File: src/SASjs.ts (hunk 1 above)
Comment (sabhas) [reply src/SASjs.ts]: refactored.

File: src/SASjs.ts [hunk 2]
```diff
@@ -558,17 +558,36 @@ export default class SASjs {
...
+        }
+      } else if (
+        config.serverType === ServerType.Sas9 &&
+        config.username &&
+        config.password
+      ) {
+        return await this.sas9JobExecutor!.execute(sasJob, data, config)
       } else {
-        return await this.jesJobExecutor!.execute(
+        return await this.webJobExecutor!.execute(
```
Comment (allanbowe) [inline src/SASjs.ts:590]: Interesting - yes, this should have been the case all along

**Review by allanbowe — APPROVED** [review]
