### PR TITLE
fix: invalid json checking

### LINKED ISSUE #446: For performance we should only parse JSON once
Currently due to validation checking we always parse the JSON twice (#431)

This is a problem for performance - SAS can provide very large JSON, and the typical enterprise customer suffers from low-powered machines

We should parse the JSON only once, and catch the errors, even if this means some code duplication.

### PR DESCRIPTION
**Pull request by medjedovicm**
## Issue

#431 
closes #446 

## Intent

Fixing the initial mechanism

## Checks

No PR (that involves a non-trivial code change) should be merged, unless all four of the items below are confirmed!  If an urgent fix is needed - use a tar file.

- [x] Code is formatted correctly (`npm run lint:fix`).
image
- [x] All unit tests are passing (`npm test`).
image
- [x] All `sasjs-cli` unit tests are passing (`npm test`).
Mocked:
image
Server:
image
- [x] All `sasjs-tests` are passing (instructions available [here](https://github.com/sasjs/adapter/blob/master/sasjs-tests/README.md)).
sasjs-tests

### CODE REVIEW

**Review by sabhas — DISMISSED** [review]

File: src/utils/isValidJson.ts [hunk 1]
```diff
@@ -2,8 +2,9 @@
  * Checks if string is in valid JSON format else throw error.
  * @param str - string to check.
  */
-export const isValidJson = (str: string) => {
+export const isValidJson = (str: string | object) => {
   try {
+    str = typeof str !== 'string' ? JSON.stringify(str) : str
```
Comment (allanbowe) [inline src/utils/isValidJson.ts:7]: If it is an object, why would we need to check if it is valid json?

File: src/utils/isValidJson.ts [hunk 2]
```diff
@@ -2,8 +2,9 @@
  * Checks if string is in valid JSON format else throw error.
  * @param str - string to check.
  */
-export const isValidJson = (str: string) => {
+export const isValidJson = (str: string | object) => {
```
Comment (allanbowe) [inline src/utils/isValidJson.ts:5]: If it is an object, why would we need to JSON parse it?

**Review by allanbowe — CHANGES_REQUESTED** [review]

File: src/test/utils/isValidJson.spec.ts [hunk 3]
```diff
@@ -0,0 +1,31 @@
+import { isValidJson } from '../../utils'
+
+describe.only('jsonValidator', () => {
```
Comment (krishna-acondy) [inline src/test/utils/isValidJson.spec.ts:3]: Only should be removed.

**Review by krishna-acondy — DISMISSED** [review]

**Review by sabhas — APPROVED** [review]

**Review by VladislavParhomchik — APPROVED** [review]

**Review by allanbowe — APPROVED** [review]
