### PR TITLE
fix: sas fails with verifying credentials

### LINKED ISSUE #381: Sometimes on first login try, we get an error, even tho credentials are good.
On second try login is successfull.

### PR DESCRIPTION
**Pull request by medjedovicm**
## Issue

fixes #381

## Intent

When during login SAS fails on verifying credential, resend the request with newly parsed CSRF token.

## Implementation

AuthManager - login()

## Checks

- [x] Code is formatted correctly (`npm run lint:fix`).
- [x] All unit tests are passing (`npm test`).
image
- [ ] All `sasjs-cli` unit tests are passing (`npm test`).
- [x] All `sasjs-tests` are passing (instructions available [here](https://github.com/sasjs/adapter/blob/master/sasjs-tests/README.md)).
sasjs-tests

### CODE REVIEW

**Comment by medjedovicm** [comment]
Notice: On SAS9, 3 sasjs-tests are failing due to these issues:

#409 #394 and invalid name sent to SAS issue (no issue created yet)

File: src/auth/AuthManager.ts [hunk 1]
```diff
@@ -34,7 +34,8 @@ export class AuthManager {
 
     this.userName = loginParams.username
 
-    const { isLoggedIn, loginForm } = await this.checkSession()
+    let { isLoggedIn, loginForm } = await this.checkSession()
```
Comment (YuryShkoda) [inline src/auth/AuthManager.ts:37]: it can be `const`

File: src/auth/AuthManager.ts [hunk 2]
```diff
@@ -77,6 +70,26 @@ export class AuthManager {
     }
   }
 
+  private async sendLoginRequest(loginForm: any, loginParams: any) {
```
Comment (YuryShkoda) [inline src/auth/AuthManager.ts:73]: `loginForm` and `loginParams` should be of tyoe `{}`

**Review by YuryShkoda — DISMISSED** [review]

File: sasjs-tests/src/App.tsx [hunk 3]
```diff
@@ -13,14 +13,19 @@ const App = (): ReactElement<{}> => {
 
   useEffect(() => {
     if (adapter) {
-      setTestSuites([
+      let testSuites = [
```
Comment (sabhas) [inline sasjs-tests/src/App.tsx:16]: should use const instead of let

File: src/auth/AuthManager.ts (hunk 1 above)
Comment (sabhas) [inline src/auth/AuthManager.ts:37]: why use let instead of const? As these variables ( isLoggedIn and loginForm ) are not being reassigned, its better to use const.

File: src/auth/AuthManager.ts [hunk 4]
```diff
@@ -44,25 +45,17 @@ export class AuthManager {
...
-        Accept: '*/*'
-      }
-    )
+    let loginResponse = await this.sendLoginRequest(loginForm, loginParams)
 
     let loggedIn = isLogInSuccess(loginResponse)
 
     if (!loggedIn) {
+      if (isCredentialsVerifyError(loginResponse)) {
+        let newLoginForm = await this.getLoginForm(loginResponse)
```
Comment (sabhas) [inline src/auth/AuthManager.ts:54]: should be const instead of let

**Review by YuryShkoda — APPROVED** [review]
