### PR TITLE
fix(special-missing): fix convertToCSV format object

### LINKED ISSUE #624: Sasjs-tests failed on SAS9 (special missings)
image

### PR DESCRIPTION
**Pull request by YuryShkoda**
## Issue

Closes #624

## Intent

- Fix special missing values support in `request` method.

## Implementation

- Fixed sending format object to `convertToCSV` utility.

## Checks

No PR (that involves a non-trivial code change) should be merged, unless all items below are confirmed!  If an urgent fix is needed - use a tar file.

- [x] All `sasjs-cli` unit tests are passing (`npm test`).
Mocked:
image
Server (without `request.spec.server`):
image
- [x] All `sasjs-tests` are passing (instructions available [here](https://github.com/sasjs/adapter/blob/master/sasjs-tests/README.md)).
Viya:
image
SAS9:
image
- [x] [Data Controller](https://datacontroller.io) builds and is functional on both SAS 9 and Viya
Viya:
image
SAS9:
image

### CODE REVIEW

File: src/utils/convertToCsv.ts [hunk 1]
```diff
@@ -3,7 +3,7 @@
  * @param data - the array of JSON objects to convert.
  */
 export const convertToCSV = (
-  data: any,
+  data: Array<any>,
```
Comment (medjedovicm) [inline src/utils/convertToCsv.ts:6]: This is a completely visual thing, but in the rest of the project I think we use `Type[]` or in this case `any[]`. Or if I am wrong if it is the other way around, we should put whichever is more consistent.

**Review by medjedovicm — DISMISSED** [review]

**Review by VladislavParhomchik — DISMISSED** [review]

File: src/utils/convertToCsv.ts (hunk 1 above)
Comment (YuryShkoda) [reply src/utils/convertToCsv.ts:6]: good point

**Review by allanbowe — APPROVED** [review]

**Review by medjedovicm — APPROVED** [review]
