### PR TITLE
fix: sas9JobExecutor issues

### LINKED ISSUE #588: Sas9JobExecutor does not append request in SasRequests array

### PR DESCRIPTION
**Pull request by medjedovicm**
## Issue

Fixes #588 

## Intent

- sas9JobExecutor not returning responses
- sas9JobExecutor not appending requests to SasRequests

## Checks

No PR (that involves a non-trivial code change) should be merged, unless all items below are confirmed!  If an urgent fix is needed - use a tar file.

- [x] All `sasjs-cli` unit tests are passing (`npm test`).
Mocked:
image
Server:
image
- [x] All `sasjs-tests` are passing (instructions available [here](https://github.com/sasjs/adapter/blob/master/sasjs-tests/README.md)).
SAS VIYA:
image
SAS9:
image
- [x] [Data Controller](https://datacontroller.io) builds and is functional on both SAS 9 and Viya

### CODE REVIEW

**Review by VladislavParhomchik — DISMISSED** [review]

File: src/job-execution/Sas9JobExecutor.ts [hunk 1]
```diff
@@ -18,6 +19,7 @@ export class Sas9JobExecutor extends BaseJobExecutor {
     serverUrl: string,
     serverType: ServerType,
     private jobsPath: string,
+    private requestClientSingle: RequestClient,
```
Comment (sabhas) [inline src/job-execution/Sas9JobExecutor.ts:22]: can't it be renamed to just requestClient? What's the need for adding Single in variable name?

**Review by sabhas — APPROVED** [review]

**Review by sabhas — APPROVED** [review]

**Review by allanbowe — APPROVED** [review]
