### PR TITLE
fix: update error message when folder not found

### LINKED ISSUE #477: Improve console message when folder not found
This issue is related to https://github.com/sasjs/cli/issues/773

### PR DESCRIPTION
**Pull request by sabhas**
## Issue
closes #477

## Intent

If the client/secret do not have the correct groups applied, then it can be the case that the target folder is not found when doing a sasjs deploy. This can be confusing when the user opens SAS Drive and sees that the folder does in fact exist. So, we updated error message to give user a better  understanding of error.

# Implementation
* Added `RootFolderNotFoundError` class that inherits from `Error`.
* Decoded access token if available and added scopes to the error message.
* Throw `RootFolderNotFoundError` in `SASViyaApiClient` if the root folder is not present.
* Fixed commit message git hook to allow dashes.

## Checks

No PR (that involves a non-trivial code change) should be merged, unless all four of the items below are confirmed!  If an urgent fix is needed - use a tar file.

- [x] Code is formatted correctly (`npm run lint:fix`).
image
- [x] All unit tests are passing (`npm test`).
image
- [x] All `sasjs-cli` unit tests are passing (`npm test`).
Mocked:
image
Server:
image
- [x] All `sasjs-tests` are passing (instructions available [here](https://github.com/sasjs/adapter/blob/master/sasjs-tests/README.md)).
image

### CODE REVIEW

File: src/SASViyaApiClient.ts [hunk 1]
```diff
@@ -610,7 +611,8 @@ export class SASViyaApiClient {
     parentFolderPath?: string,
     parentFolderUri?: string,
     accessToken?: string,
-    isForced?: boolean
+    isForced?: boolean,
+    serverUrl?: string
```
Comment (krishna-acondy) [inline src/SASViyaApiClient.ts:615]: `serverUrl` does not need to be passed in here - it is available as an instance variable in the `SASViyaApiClient` class.

File: src/SASViyaApiClient.ts [hunk 2]
```diff
@@ -36,6 +36,7 @@ import { isAuthorizeFormRequired } from './auth/isAuthorizeFormRequired'
 import { RequestClient } from './request/RequestClient'
 import { prefixMessage } from '@sasjs/utils/error'
 import * as mime from 'mime'
+import jwtDecode from 'jwt-decode'
```
Comment (krishna-acondy) [inline src/SASViyaApiClient.ts:39]: `jwt-decode` is a transitive dependency installed via `@sasjs/utils`. I think it'd be better to keep it that way and add a helper function there that returns the decoded token - that way we could also add an interface for it and make it type safe.

File: src/SASViyaApiClient.ts [hunk 3]
```diff
@@ -630,7 +632,17 @@ export class SASViyaApiClient {
         )
         const newFolderName = `${parentFolderPath.split('/').pop()}`
         if (newParentFolderPath === '') {
-          throw new Error('Root folder has to be present on the server.')
+          let error: string = `Root folder ${parentFolderPath} was not found\nPlease check ${serverUrl}/SASDrive\nIf folder DOES exist then it is likely a permission problem\n`
+          if (accessToken) {
+            const tokenResponse: any = jwtDecode(accessToken)
```
Comment (krishna-acondy) [inline src/SASViyaApiClient.ts:637]: See comment above on `jwt-decode` import.

**Review by krishna-acondy — CHANGES_REQUESTED** [review]
Please make sure to run the CLI tests and `sasjs-tests` and update the checkboxes in the PR description as well.

**Review by VladislavParhomchik — APPROVED** [review]

**Review by medjedovicm — DISMISSED** [review]

File: src/SASViyaApiClient.ts [hunk 4]
```diff
@@ -381,7 +387,18 @@ export class SASViyaApiClient {
         )
         const newFolderName = `${parentFolderPath.split('/').pop()}`
         if (newParentFolderPath === '') {
-          throw new Error('Root folder has to be present on the server.')
+          let error: string = `Root folder ${parentFolderPath} was not found\nPlease check ${this.serverUrl}/SASDrive\nIf folder DOES exist then it is likely a permission problem\n`
+          if (accessToken) {
+            const decodedToken: DecodedToken = decodeToken(accessToken)
+            console.log(decodedToken)
```
Comment (krishna-acondy) [inline src/SASViyaApiClient.ts:393]: This needs to go.

File: src/SASViyaApiClient.ts [hunk 5]
```diff
@@ -381,7 +387,18 @@ export class SASViyaApiClient {
...
+            const scope = decodedToken.scope
+            error =
+              error + `The following scopes are contained in client/secret:\n`
```
Comment (krishna-acondy) [inline src/SASViyaApiClient.ts:396]: Shouldn't this say `The following scopes are contained in the access token:`?

**Review by VladislavParhomchik — APPROVED** [review]

File: src/SASViyaApiClient.ts [hunk 6]
```diff
@@ -381,7 +387,17 @@ export class SASViyaApiClient {
...
         const newFolderName = `${parentFolderPath.split('/').pop()}`
         if (newParentFolderPath === '') {
-          throw new Error('Root folder has to be present on the server.')
+          let error: string = `Root folder ${parentFolderPath} was not found\nPlease check ${this.serverUrl}/SASDrive\nIf folder DOES exist then it is likely a permission problem\n`
+          if (accessToken) {
+            const decodedToken: DecodedToken = decodeToken(accessToken)
+            const scope = decodedToken.scope
+            error =
+              error + `The following scopes are contained in access token:\n`
+            scope.forEach((element: any) => {
```
Comment (krishna-acondy) [inline src/SASViyaApiClient.ts:396]: `error += scope.join('\n')` would be better in my opinion.

File: src/SASViyaApiClient.ts [hunk 7]
```diff
@@ -381,7 +387,17 @@ export class SASViyaApiClient {
         )
         const newFolderName = `${parentFolderPath.split('/').pop()}`
         if (newParentFolderPath === '') {
```
Comment (krishna-acondy) [inline src/SASViyaApiClient.ts:389]: It would be great if we could extract this entire section into a function and add test(s) for it.

**Comment by VladislavParhomchik** [comment]
Server sasjs-cli tests Failed:
image

File: src/SASViyaApiClient.ts (hunk 6 above)
Comment (sabhas) [reply src/SASViyaApiClient.ts:396]: then we wouldn't be able to add star or dash as prefix. If prefix is necessary we would have to add another statement as
`scope = scope.map(element => '* ' + element)`
what do you suggest?

Comment (krishna-acondy) [reply src/SASViyaApiClient.ts:396]: Ah, apologies, I didn't notice the `*`.
Yes, I think the `map` and `join` approach is preferable since we will only be adding to the `error` string once instead of multiple times.

File: .git-hooks/commit-msg [hunk 8]
```diff
@@ -6,7 +6,7 @@ GREEN="\033[1;32m"
 # temporary file which holds the message).
 commit_message=$(cat "$1")
 
-if (echo "$commit_message" | grep -Eq "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z0-9 \-\*]+\))?!?: .+$") then
+if (echo "$commit_message" | grep -Eq "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-z0-9 -\*]+\))?!?: .+$") then
```
Comment (krishna-acondy) [inline .git-hooks/commit-msg:9]: This was causing the check to fail when the commit message had dashes: `-` does not need to be escaped.

File: src/SASViyaApiClient.ts [hunk 9]
```diff
@@ -381,7 +381,11 @@ export class SASViyaApiClient {
...
-          throw new Error('Root folder has to be present on the server.')
+          throw new RootFolderNotFoundError(
```
Comment (krishna-acondy) [inline src/SASViyaApiClient.ts:384]: This is now its own error type - `RootFolderNotFoundError`. If required, we can handle it differently on the calling side.

**Comment by krishna-acondy** [comment]
@allanbowe / @VladislavParhomchik / @medjedovicm I've pushed another commit which refactors this refactors this fix to bring it in line with how we handle other errors.

I've also updated the implementation section.

**Review by krishna-acondy — APPROVED** [review]

**Review by allanbowe — APPROVED** [review]
