### PR TITLE
fix(utility): improved 'isUrl' utility

### LINKED ISSUE #325: improve url validation
url like `https://test` should be considered as a valid url

### PR DESCRIPTION
**Pull request by YuryShkoda**
## Issue

closes #325 

## Intent

Improve url validation

## Checks

- [x] Code is formatted correctly (`npm run lint:fix`).
- [x] All unit tests are passing (`npm test`).
- [ ] All `sasjs-cli` unit tests are passing (`npm test`).
- [ ] All `sasjs-tests` are passing (instructions available [here](https://github.com/sasjs/adapter/blob/master/sasjs-tests/README.md)).

### CODE REVIEW

File: src/utils/isUrl.ts [hunk 1]
```diff
@@ -3,14 +3,11 @@
  * @param url - string to check.
  */
 export const isUrl = (url: string): boolean => {
-  const pattern = new RegExp(
-    '^(http://|https://)[a-z0-9]+([-.]{1}[a-z0-9]+)*.[a-z]{2,5}(:[0-9]{1,5})?(/.*)?$',
-    'gi'
-  )
+  try {
```
Comment (krishna-acondy) [inline src/utils/isUrl.ts:6]: Might be a good idea to add tests for this function.

Comment (YuryShkoda) [reply src/utils/isUrl.ts:8]: test is provided

**Review by krishna-acondy — APPROVED** [review]
