### PR TITLE
Issue87

### LINKED ISSUE #87: `executeJobViaJesApi` error handling if job does not exist
## Current behavior
If job does not exist, execution of `request` method fails without finishing.

## Desired behavior
If job does not exist, execution finishes and result includes the message about job not found.

---
Docs link: https://adapter.sasjs.io/classes/reflection-708.reflection-180.sasjs.html#request

### PR DESCRIPTION
**Pull request by medjedovicm**
Closes #87

### CODE REVIEW

**Review by krishna-acondy — DISMISSED** [review]

File: src/SASViyaApiClient.ts [hunk 1]
```diff
@@ -1001,9 +1001,21 @@ export class SASViyaApiClient {
 
     if (allJobsInFolder) {
       const jobSpec = allJobsInFolder.find((j: Job) => j.name === jobName)
+
+      if (!jobSpec) {
+        console.error('Job was not found.')
```
Comment (YuryShkoda) [inline src/SASViyaApiClient.ts:1006]: delete extra console.error()

File: src/SASViyaApiClient.ts [hunk 2]
```diff
@@ -1001,9 +1001,21 @@ export class SASViyaApiClient {
...
+        throw new Error('Job was not found.')
+      }
+
       const jobDefinitionLink = jobSpec?.links.find(
         (l) => l.rel === 'getResource'
       )?.href
+
+      if (!jobDefinitionLink) {
+        console.error('Job definition URI was not found.')
```
Comment (YuryShkoda) [inline src/SASViyaApiClient.ts:1015]: delete extra console.error()

**Review by YuryShkoda — CHANGES_REQUESTED** [review]

**Review by YuryShkoda — APPROVED** [review]
