### PR TITLE
fix: update code for extracting JSON URL on viya4 when debug is enabled

### LINKED ISSUE #689: fetching log with DEBUG enabled on Viya 4 with WEB approach
The web approach uses the JES web app to fetch job content (slow but reliable)

In this case, when debug is enabled, the JSON is embedded in an iframe and must be extracted by the adapter

The Viya 3.5 adapter code is as follows:

image

However on Viya 4, the iframe looks like this:
```
<iframe style="width: 99%; height: 500px; background-color:Canvas;" src=/SASJobExecution/?_fileid=98e16c87-45c1-4819-862d-24eeacee15f9></iframe>
```

### PR DESCRIPTION
**Pull request by sabhas**
## Issue

closes #689 

## Intent

- viya4 returns a bit different iframe than viya 3.5. Adjusted the code to handle both cases.

## Implementation

- used regex instead of simple string to extract JSON URL from the iframe element.

## Checks

No PR (that involves a non-trivial code change) should be merged, unless all items below are confirmed!  If an urgent fix is needed - use a tar file.

- [ ] All `sasjs-cli` unit tests are passing (`npm test`).
- [ ] All `sasjs-tests` are passing (instructions available [here](https://github.com/sasjs/adapter/blob/master/sasjs-tests/README.md)).
- [ ] [Data Controller](https://datacontroller.io) builds and is functional on both SAS 9 and Viya

### CODE REVIEW

File: src/utils/parseViyaDebugResponse.ts [hunk 1]
```diff
@@ -16,10 +16,15 @@ export const parseSasViyaDebugResponse = async (
   requestClient: RequestClient,
   serverUrl: string
 ) => {
+  // On viya 3.5, iframe is like <iframe style="width: 99%; height: 500px" src="..."></iframe>
+  // On viya 4, iframe is like <iframe style="width: 99%; height: 500px; background-color:Canvas;" src=...></iframe>
+
   const iframeStart = response.split(
-    '<iframe style="width: 99%; height: 500px" src="'
+    /<iframe style="width: 99%; height: 500px" src="|<iframe style="width: 99%; height: 500px; background-color:Canvas;" src=/
```
Comment (medjedovicm) [inline src/utils/parseViyaDebugResponse.ts:23]: I am bit afraid anytime that styles could be changed, so I suggest we use something more generic as a regex.
For example: `/<iframe style=.*src=.*/`

It would match in all cases.

**Review by medjedovicm — APPROVED** [review]
