### PR TITLE
fix: parse the logs before appending the request to request array whe…

### LINKED ISSUE #718: Requests are being served as JSON instead of plaintext log #293
Screenshot from 2022-06-09 23-05-38

### PR DESCRIPTION
**Pull request by sabhas**
…n server type is sasjs

## Issue

closes #718 

## Intent

* show the log in request modals as plain text

## Implementation

* when server type is sasjs parse the logs before appending the request to the request history array because logs returned from sasjs server is of bit different shape as compared to viya and sas9. 

## Checks

No PR (that involves a non-trivial code change) should be merged, unless all items below are confirmed!  If an urgent fix is needed - use a tar file.

- [ ] All `sasjs-cli` unit tests are passing (`npm test`).
- (CI Runs this) All `sasjs-tests` are passing. If you want to run it manually (instructions available [here](https://github.com/sasjs/adapter/blob/master/sasjs-tests/README.md)).
- [ ] [Data Controller](https://datacontroller.io) builds and is functional on both SAS 9 and Viya

### CODE REVIEW

**Review by medjedovicm — DISMISSED** [review]
Looks good, I deployed `sasjs-tests` SAS services and re-run the CI.

File: src/job-execution/WebJobExecutor.ts [hunk 1]
```diff
@@ -169,19 +169,27 @@ export class WebJobExecutor extends BaseJobExecutor {
...
 
           this.requestClient!.appendRequest(resObj, sasJob, config.debug)
 
+          if (
+            this.serverType === ServerType.Sasjs &&
+            res.result._webout.length < 1
+          ) {
+            throw new JobExecutionError(
+              0,
+              'Job execution failed',
```
Comment (allanbowe) [inline src/job-execution/WebJobExecutor.ts:188]: Is there more information we can provide here?  http response code perhaps?  And perhaps we can be more specific (eg the job executed, but no webout was returned)

Comment (allanbowe) [reply src/job-execution/WebJobExecutor.ts:188]: suggestion:

> No webout was returned by job $(program). Servertype is SASJS and the calling function is WebJobExecutor. Please check the SAS log for more info.

**Review by allanbowe — APPROVED** [review]

**Review by YuryShkoda — APPROVED** [review]
